# Generated by Django 3.1.1 on 2020-12-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('confirm_password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
    ]
