# Generated by Django 3.1.1 on 2020-12-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_add',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sign_up_add',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
