# Generated by Django 3.1.1 on 2020-12-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201219_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign_up_add',
            new_name='sign_up',
        ),
    ]
