# Generated by Django 3.1.1 on 2020-12-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201222_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign_up',
            new_name='sign_up_add',
        ),
    ]
